name: pytorch_env
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch=2.0.*
  - pytorch-cuda=11.8
  - torchvision
  - torchaudio
  # cudatoolkit=11.8 제거 - PyTorch에서 자체적으로 CUDA 의존성 관리
  - ipykernel
  - ipywidgets
  - jupyterlab
  - matplotlib
  - numpy
  - pandas
  - pillow
  - scikit-learn
  - scipy
  - tqdm
  # - tensorrt 주석 처리 - 호환성 문제로 인해 제거
  - pip
  - pip:
    - tensorboard
    - opencv-python
